package advent2018Kotlin.test

import advent2018Kotlin.D17
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class D17Tests {
    @Test
    fun shouldParse() {
        assertThat(D17.parse(
                """
                x=495, y=2..7
                y=7, x=495..501
                x=501, y=3..7
                x=498, y=2..4
                x=506, y=1..2
                x=498, y=10..13
                x=504, y=10..13
                y=13, x=498..504
                """.trimIndent().trim()
        ).render()).isEqualTo(
                """
                ......+.......
                ............#.
                .#..#.......#.
                .#..#..#......
                .#..#..#......
                .#.....#......
                .#.....#......
                .#######......
                ..............
                ..............
                ....#.....#...
                ....#.....#...
                ....#.....#...
                ....#######...
                """.trimIndent().trim())
    }
}